services:
  - type: web
    name: oketch
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
